[project]
version = "1.0.0"
name = "rys"
language = "c"
standard = "c11"
compiler = "gcc"

[directories]
sources = "src"
include = "include"
build = "build"

[dependencies]

[libraries]
lib_dirs = []
libraries = []
